// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderParams = { width: number, height: number, rot_x: number, rot_y: number, rot_z: number, auto_rotate: boolean, rotate_speed_x: number, rotate_speed_y: number, rotate_speed_z: number, zoom: number, charset: string, shading: string, light_x: number, light_y: number, light_z: number, ambient: number, invert: boolean, color_mode: string, };
